name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to PyPI?"
        required: true
        default: false
        type: boolean
      sign:
        description: "Sign the release?"
        required: true
        default: true
        type: boolean
      tag:
        description: "Tag to use for release"
        required: true

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.tag || github.ref }}
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.publish == 'true'
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/p/citric
    permissions:
      id-token: write # IMPORTANT: Used by PyPI trusted publishing
      contents: write # IMPORTANT: Used to attach signing artifacts to the published release

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.8.11
    - uses: svenstaro/upload-release-action@v2
      with:
        file: dist/**
        tag: ${{ github.event.inputs.tag || github.ref }}
        overwrite: false
        file_glob: true

  # Move this up when PyPI supports signing
  sign:
    name: Sign the distribution package
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.sign == 'true'
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write # IMPORTANT: Used to attach signing artifacts to the published release
      id-token: write # IMPORTANT: Used by sigstore

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
          upload-signing-artifacts: true
      - uses: svenstaro/upload-release-action@v2
        with:
          file: dist/*.sig*
          tag: ${{ github.event.inputs.tag || github.ref }}
          overwrite: true
          file_glob: true
